### ISSUE TITLE
Release v0.7

### ISSUE THREAD

**Issue by quozl** [sugarlabs/gwebsockets#2]
* [x] try using a later autobahn, per fe928e76c0751d9ae11d273225b06c53dca7362b,
* [x] tag v0.5,
* [x] release to pypi.python.org, (this may require obtaining access as a new maintainer),
* [x] <s>report bug to bugs.debian.org advising of new upstream release and new maintainer,</s>(debian package has a valid watch file)
* [x] report same to fedora.

**Comment by Aniket21mathur** [comment]
@quozl  I am willing to make a release. Do we have to follow the same norms as for ASLO or something different. Please help.Thanks!

**Comment by quozl** [comment]
It's not an activity.  Very different.  It is a component used by Sugar to support the Sugar Web activities.  I've reviewed the source code and adjusted the checklist above.

**Comment by Aniket21mathur** [comment]
-  try using a later autobahn, per fe928e7
Sorry didn't understood what exactly do you mean by this line.
Not able to understand how Do I test it. Thanks!

**Comment by quozl** [comment]
There's a dependency on autobahn in the source code, you can find it with `git grep`.  No need to have asked me about it.

gwebsockets can be tested by installing on a system that runs Sugar, then start one of the Sugar activities written in JavaScript.  I think it is used for access to Journal.  Read the source code for one of the activities, and `sugar-activity-web`, and search for the `SUGAR_APISOCKET_*` environment variables.

You really have to work these things out yourself, because (a) I don't know much about it, and (b) nobody else seems to know or is too busy to answer.  We lost a key developer suddenly.  Read all the source code.

**Comment by quozl** [comment]
Any progress?

**Comment by Aniket21mathur** [comment]
@quozl  being a part of port to python 3 project I also added this to my proposal time line for GSoC '19.
But I don't find any issue in making a release early. I mailed to sysadmin@sugarlabs.org for adding me as a maintainer on pypi.python.org .

**Comment by quozl** [comment]
I don't have access to pypi.python.org for the gwebsockets project, sorry.  As an organisation, we may not have access.  The project was created by Daniel Narvaez (@dnarvaez), and he did not leave us any access.  I've checked a copy of his disabled account on sunjammer.sugarlabs.org but I've not been able ot identify anything needed.

You may need to help us [engage the PyPI process](https://pypi.org/help/#project-name-claim).

Also, please check to see if the other project [gwebsocket](https://pypi.org/project/gwebsocket/) is suitable as a replacement.  It has a later release date, but has had no release since 2016.

**Comment by Aniket21mathur** [comment]
I found out that the Python Packaging Authority have a [mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/l) and an IRC channel.
Should I draft an email from Sugarlabs, get it reviewed through our mailing list and then send it to their mailing list?

**Comment by quozl** [comment]
No.  [PEP 541](https://www.python.org/dev/peps/pep-0541/#implementation) is clear.  It also says six weeks are needed to prove failure of reachability.  There are other conditions there.  Have something to release before starting the process.

**Comment by quozl** [comment]
I've tagged v0.5 and made a [Python 3 gwebsockets package](http://people.sugarlabs.org/~quozl/python3-gwebsockets_0.5+git20190730_all.deb) to enable wider testing of https://github.com/sugarlabs/sugar/pull/844.

**Comment by Aniket21mathur** [comment]
> I've tagged v0.5 and made a [Python 3 gwebsockets package](http://people.sugarlabs.org/~quozl/python3-gwebsockets_0.5+git20190730_all.deb) to enable wider testing of [sugarlabs/sugar#844](https://github.com/sugarlabs/sugar/pull/844).

Thanks.

**Comment by Aniket21mathur** [comment]
@quozl should I write access requesting e-mail to PPA now?

**Comment by quozl** [comment]
No, let me do that.  You may raise a bug with Debian to have it packaged;
* priority wishlist,
* package gwebsockets from tag v0.5 here,
* change `debian/watch` to this repository.

For your interest, the method of making the package was;
* `python setup.py sdist` ,
* `sudo apt source python-gwebsockets` ,
* unpack the _dist/gwebsockets-0.5.tar.gz_ file,
* rename the _gwebsockets-0.5_ directory to _python3-gwebsockets-0.5+git20190730_,
* rename the _dist/gwebsockets-0.5.tar.gz_ file to _python3-gwebsockets_0.5+git20190730.orig.tar.gz_,
* copy the _debian_ directory from _python-gwebsockets_ to _python3-gwebsockets-0.5+git20190730_,
* for the files in the _debian_ directory change the package name and version number in `changelog`, and use Python 3 in `control` and `rules`,
* build the package with `debuild` ,
* test install the package on a virtual machine using `dpkg -i *deb`,
* test import on the virtual machine,
* upload the package with `dcmd rsync *changes ...`

**Comment by quozl** [comment]
pypa/
warehouse/
issues/
6309

**Comment by Aniket21mathur** [comment]
No response on https://github.com/pypa/warehouse/issues/6309 yet :confused:

**Comment by quozl** [comment]
Response to deleted comment from @Aniket21mathur,
> No response on pypa/warehouse#6309 yet

I'll worry after six weeks.

**Comment by quozl** [comment]
I'm owner on PyPi now.

**Comment by srevinsaju** [comment]
As release 0.7 is done, is this focused on v0.8?

**Comment by quozl** [comment]
Thanks for asking.  Release 0.7 is in progress.  While we have merged commits, we don't yet have;

* [x] a release git tag,
* [x] upload to download.sugarlabs.org,
* [x] upload to pypi.org (which may require changes and a 0.8 release),

For your interest, I also have a custom Debian packaging of the 0.7 release built for Ubuntu 20.04 as package name _python3-gwebsockets_, and have been building other custom packages of Sugar and activities in order to test gwebsockets properly.
