### ISSUE TITLE
Tests are failing after upgrade of autobahn or twisted

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/gwebsockets#5]
On running `python3 setup.py test` with autobahn v0.6.5. I got the following traceback
```
ImportError: Failed to import test module: test_server
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/aniket1/activities/gwebsockets/gwebsockets/tests/test_server.py", line 6, in <module>
    from autobahn.twisted.websocket import WebSocketClientProtocol
  File "/home/aniket1/activities/gwebsockets/.eggs/autobahn-0.6.5-py3.6.egg/autobahn/__init__.py", line 19, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'
```
As per [this](https://stackoverflow.com/questions/39130957/importerror-no-module-named-version-when-importing-mechanize), seems like the old version do not support python 3.

I removed the hard-coded version and tested with the latest version. The above traceback was gone, but I do got

```
 File "/home/aniket1/activities/gwebsockets/gwebsockets/server.py", line 120, in _read_data_cb
    self._request.write(data)
TypeError: string argument expected, got 'bytes'

```
Now this seems to be related to python 3 port. 
@pro-panda @quozl have a look.

**Comment by rhl-bthr** [comment]
Check if the argument is of type bytes. If it is, convert it to string
This would help in supporting Python 2 and 3 at the same time

**Comment by Aniket21mathur** [comment]
Thanks fixed that. But the tests still fail with errors like:-
```
Traceback (most recent call last):
  File "/home/aniket1/activities/gwebsockets/gwebsockets/server.py", line 123, in _read_data_cb
    self._do_handshake()
  File "/home/aniket1/activities/gwebsockets/gwebsockets/server.py", line 74, in _do_handshake
    response = protocol.make_handshake(self._request)
  File "/home/aniket1/activities/gwebsockets/gwebsockets/protocol.py", line 233, in make_handshake
    headers.get('upgrade')))
gwebsockets.protocol.BadRequestException: No WebSocket UPGRADE hdr: None
```
and 
```
twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<<class 'twisted.internet.tcp.Client'> to ('localhost', 33709) at 7f86bd1c1400>
```

**Comment by quozl** [comment]
I presume some change has happened that needs a change to gwebsockets.  I suggest one or more of;
* make a local branch of gwebsockets before the Port to Python 3,https://github.com/sugarlabs/gwebsockets/commit/777954a3a97de2e62817f3180d5b3bc530caff65, and iterate through each later version of autobahn until you find when the regression began,
* downgrade autobahn one version at a time to see if a previous version works,
* downgrade autobahn one commit at a time to see when the regression began,
* read the autobahn documentation for 0.6.5 and ensure each use of it in gwebsockets is compliant.

**Comment by Aniket21mathur** [comment]
Thanks did some research and work around. The reason for this traceback is the fact that python 2 and 
python 3 handles StringIO objects differently. The code 

```
def make_handshake(request):
    request_line = request.readline()
    if not request_line.startswith("GET"):
        raise BadRequestException("The method should be GET")

    message = httplib.HTTPMessage(request)
    headers = dict(message)
```
in `gwebsockets/protocol.py` is the reason why the tests fail. For python 3 `httplib.HTTPMessage(request)` is not able to extract the headers from request (a StringIO object) and hence results in empty `message`, whereas for python 2 it works.

What is needed is to find a method to convert an StringIO object into dict, or do it manually. I am not able to find any function yet. 

I also tried python 2 branch with autobahn > 0.6.5, and got this traceback

```
tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_server'

```
It doesn't seems to be anything related to the code, looks like the process was not able to import the 'test_server' module.

Thanks!

**Comment by quozl** [comment]
> What is needed is to find a method to convert an StringIO object into dict, or do it manually. I am not able to find any function yet.

_StringIO_ is lke a _file_.  Can you use _readlines_ method or give it to _http.client.HTTPMessage_?

**Comment by Aniket21mathur** [comment]
> Can you use _readlines_

Yes I am able to use readline, works fine checked by using print.

> or give it to _http.client.HTTPMessage_

Yes no error produced on passing it to _ http.client.HTTPMessage_ . But ultimately these lines 
```
 message = httplib.HTTPMessage(request)
 headers = dict(message)
```
are returning headers = {}, an empty dict.

Is it neccessary to use StringIO ? Cannot we use a simple string?

**Comment by quozl** [comment]
As far as I can tell, _StringIO_ was used only because _httplib_ expected a _file_-derived type.

**Comment by Aniket21mathur** [comment]
Thanks, I have replaced _StringIO_ with _str_. I have a patch here https://github.com/Aniket21mathur/gwebsockets/commit/a8588281b0c174004ee8c2df234f5578f0b20280, please review. 

Now on running test, I am getting this error:
```
 File "/home/aniket1/Desktop/gwebsockets/gwebsockets/server.py", line 85, in _read_data_cb
    data = stream.read_bytes_finish(result).get_data().decode("utf-8")
GLib.Error: g-io-error-quark: Error receiving data: Connection reset by peer (44)
```

**Comment by quozl** [comment]
Connection reset by peer.

Means that the peer directed the connection to reset.

Also, given the partial traceback you posted refers to the server
code, it means the peer is the test program.  The test program
probably terminated prematurely.  Look for why, using a debugger.

Wild guess; something the server said to the test program was not
acceptable.

You may use connection monitoring tools, such as tcpdump, to confirm
that the connection is being reset.  Some knowledge of TCP/IP at
protocol layer is helpful.  A connection will consist of a SYN, SYN
ACK, ACK, data, and then either a FIN, FIN ACK for normal closure, or
a RST for a reset.  tcpdump shows these as [S] for SYN, [F] for FIN,
and [R] for RST.  Capture a successful connection using code before
the port, and compare against the failed connection.

**Comment by Aniket21mathur** [comment]
Thanks. I looked at the source code again, did some work around. I think that there are much chances that the tests failed due to the different output and input formats ("str" or "bytes") that functions expect and produce in python and python 3. 

```
File "/home/aniket1/Desktop/gwebsockets/gwebsockets/server.py", line 85, in _read_data_cb
    data = stream.read_bytes_finish(result).get_data().decode("utf-8")
GLib.Error: g-io-error-quark: Error receiving data: Connection reset by peer (44)
```
the traceback is produced because _result_ is not something expected.
The _result_ is produced by 
```
def _response_write_cb(self, stream, result, user_data):
        stream.write_bytes_finish(result)
        self._ready = True

def _do_handshake(self):
        self._request.seek(0)
        response = protocol.make_handshake(self._request)

        stream = self._connection.get_output_stream()
        stream.write_bytes_async(GLib.Bytes.new(response.encode("utf-8")),
                                 GLib.PRIORITY_DEFAULT,
                                 None, self._response_write_cb, None)
```
and is a _Gio.Task object_ object. So I am now exploring _GLib_ documentation, it may help.

**Comment by rhl-bthr** [comment]
> I think that there are much chances that the tests failed due to the different output and input formats ("str" or "bytes") that functions expect and produce in python and python 3.

Thanks. Try using a debugger to examine this further

**Comment by quozl** [comment]
What is status?  Blocking testing of the component _sugar_ port to Python 3.

**Comment by Aniket21mathur** [comment]
> What is status? Blocking testing of the component _sugar_ port to Python 3.

I am still stuck on finding the cause of the above traceback

> GLib.Error: g-io-error-quark: Error receiving data: Connection reset by peer (44)

**Comment by quozl** [comment]
Immediate cause is that the test program terminated.  You must use tcpdump or wireshark and a debugger.

If you describe how you test, then I can try it on Monday.  I've no idea how to test gwebsockets yet.

**Comment by Aniket21mathur** [comment]
I used[ this](https://www.linuxtechi.com/capture-analyze-packets-tcpdump-command-linux/) documentation, generating .pcap files and trying to analyse them using wireshark. Sorry I didn't got much time in the last two days to look into it.

**Comment by quozl** [comment]
How does the .pcap differ between Python 2 and Python 3?

**Comment by quozl** [comment]
I've reviewed this issue and the source code.  I've experimented with the tests.

* with current working directory set to the root directory of the repository, running `gwebsockets/tests/test_server.py` fails to `import gwebsockets` with a _ModuleNotFoundError_,

* installing the `python3-autobahn` package, copying the `test_server.py` file to the root directory of the repository and then running it works fine; the test passes,

* running `python3 setup.py test` bypasses the system package for _autobahn_ and downloads instead, and then it fails with a _ModuleNotFoundError_ on `from _version import __version__` as @Aniket21mathur reported in opening comment,

* removing the version dependency in `setup.py` does result in _TypeError: string argument expected, got 'bytes'_, as @Aniket21mathur reported.

So far, this appears to be a problem with the test program.  The test program is not in the Debian source package `python-gwebsockets`, and tests are not run during `debuild`.  I don't think this issue should block release and testing with Sugar and Sugar web activities.  The test program depends on much that we do not use in Sugar, such as _autobahn_ and _twisted_.

I'll change the issue title to reflect that the built-in tests are failing.

**Comment by Aniket21mathur** [comment]
Thanks for analyzing, I never thought of the problem in this way.

> don't think this issue should block release and testing with Sugar and Sugar web activities

Agreed.

**Comment by quozl** [comment]
https://github.com/sugarlabs/gwebsockets/issues/6 made built-in tests complete without error, but we don't know they are working.  Issue open until we can understand they are working.

**Comment by quozl** [comment]
Tested once more.

Using _strace_ proves running the test program from the command line does nothing with web sockets, and this is consistent with how the test program does not execute anything except a twisted GTK 3 reactor.

I guess the test program is incomplete.  So I propose to;
* [x] remove the test program,
* [x] remove the tests part of `setup.py`,
* [x] remove the `dependencies.txt`.

Can I have a second opinion please?

**Comment by rhl-bthr** [comment]
I'm okay with removing the test program. I don't see value in maintaining it

**Comment by Aniket21mathur** [comment]
> Can I have a second opinion please?

Agreed with @pro-panda

**Comment by quozl** [comment]
Tests were removed.
