### ISSUE TITLE
TypeError: string argument expected, got 'bytes'

### ISSUE THREAD

**Issue by quozl** [sugarlabs/gwebsockets#6]
Reproducer: start the Moon-19 activity in Sugar 0.115, then try to stop the activity using the stop button.

Expected result: activity stops.

Observed result: activity does not stop, and Sugar logs contain;

```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/gwebsockets/server.py", line 120, in _read_data_cb
    self._request.write(data)
TypeError: string argument expected, got 'bytes'
```

Workaround: use Frame to stop activity.

Same error was seen in https://github.com/sugarlabs/gwebsockets/issues/5, so now we know it is important to understand and fix.

**Comment by srevinsaju** [comment]
#7

**Comment by quozl** [comment]
@srevinsaju, best procedure is to put "Fixes ISSUEURL" in the commit message or the pull request, then GitHub will close the issue automatically on merge.

**Comment by srevinsaju** [comment]
Ohk @quozl some new info for me :)
