### ISSUE TITLE
gwebsockets.protocol.BadRequestException: No WebSocket UPGRADE hdr: None

### ISSUE THREAD

**Issue by quozl** [sugarlabs/gwebsockets#9]
Sugar `shell.log` contains a traceback when a web activity is asked to stop;

```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/gwebsockets/server.py", line 126, in _read_data_cb
    self._do_handshake()
  File "/usr/lib/python3.7/dist-packages/gwebsockets/server.py", line 78, in _do_handshake
    response = protocol.make_handshake(self._request)
  File "/usr/lib/python3.7/dist-packages/gwebsockets/protocol.py", line 231, in make_handshake
    headers.get('upgrade')))
gwebsockets.protocol.BadRequestException: No WebSocket UPGRADE hdr: None
```

Version tested was https://github.com/sugarlabs/gwebsockets/commit/240b189916cecf624b1ce3c6c12340a8cc357f9c.

Wireshark shows this HTTP request is received by gwebsockets when the activity starts, and there is no response from gwebsockets;
```log
GET / HTTP/1.1
Host: 127.0.0.1:35485
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
Origin: activity://com.garycmartin.moon
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: iBBCmT+TO/nOjkFHd6IaPg==
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate
Accept-Language: en-AU
```

Enabling debug logging in gwebsockets shows;

```log
1580104500.084468 DEBUG gwebsockets: Got data, length 417
```

and this indicates the data is not fragmented.

**Comment by quozl** [comment]
@pro-panda, it looks like we never properly tested @curiousguy13's work when we merged it.  :grin:

**Comment by rhl-bthr** [comment]
Yes

**Comment by curiousguy13** [comment]
> 
> 
> @pro-panda, it looks like we never properly tested @curiousguy13's work when we merged it. 😁

@quozl I didn't even know my work from 2014 was ever merged :sweat_smile:
